apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169931709
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169931709
    app.kubernetes.io/part-of: test-app-169931709
  name: java-quarkus-169931709
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169931709
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169931709
    spec:
      containers:
      - image: quay.io/hacdev/di8sgxmh-tenant/test-app-169931709/java-quarkus-169931709@sha256:12863c2ca25c8bbcc506415d2ef0c14b1d51a92618cfbe3807286de1326b36dd
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
